CREATE DATABASE IF NOT EXISTS microservice_mall DEFAULT CHARACTER SET utf8mb4;

CREATE USER IF NOT EXISTS 'canal'@'%' IDENTIFIED BY 'Canal@123456';
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
FLUSH PRIVILEGES;
