canal.instance.mysql.slaveId=1234
canal.instance.gtidon=false
canal.instance.master.address=mysql:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.tsdb.enable=false
canal.instance.dbUsername=canal
canal.instance.dbPassword=Canal@123456
canal.instance.connectionCharset=UTF-8
canal.instance.enableDruid=false

canal.instance.filter.regex=microservice_mall\\.mall_product,microservice_mall\\.mall_category,microservice_mall\\.order_main,microservice_mall\\.order_item,microservice_mall\\.order_status_log,microservice_mall\\.cart_item,microservice_mall\\.coupon_template,microservice_mall\\.coupon_user,microservice_mall\\.payment_record,microservice_mall\\.refund_main,microservice_mall\\.refund_item,microservice_mall\\.shipment,microservice_mall\\.shipment_trace,microservice_mall\\.user_account,microservice_mall\\.user_token
canal.instance.filter.black.regex=mysql\\.slave_.*

canal.mq.topic=cache-sync-default
canal.mq.dynamicTopic=cache-sync-stock:microservice_mall\\.mall_(product|category),cache-sync-order:microservice_mall\\.(order_main|order_item|order_status_log|cart_item|coupon_template|coupon_user|payment_record|refund_main|refund_item|shipment|shipment_trace),cache-sync-user:microservice_mall\\.(user_account|user_token)
canal.mq.partition=0
canal.instance.multi.stream.on=false
